#!/bin/bash
# shellcheck disable=SC2206
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS MODIFIED AUTOMATICALLY FROM TEMPLATE AND SHOULD BE RUNNABLE!

#SBATCH --job-name=data_generation_0607-1054
#SBATCH --output=data_generation_0607-1054.log

### This script works for any number of nodes, Ray will find and manage all resources
#SBATCH --nodes=1
#SBATCH --chdir=/nesi/project/uoa03669/ewin313/TropicalCycloneAI/
### Give all resources to a single Ray task, ray can manage the resources internally
#SBATCH --gpus-per-task=0
#SBATCH --time=024:00:00
#SBATCH --mem-per-cpu=2GB
#SBATCH --cpus-per-task=24


# Load modules or your own conda environment here

source load-environment.sh

# ===== Call your code below =====
python TrainingDataGeneration/GenerateTrainingData.py 1000 25 5 5 /nesi/project/uoa03669/ewin313/storm_data/v6 --include_grids

