#!/bin/bash
# shellcheck disable=SC2206
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS MODIFIED AUTOMATICALLY FROM TEMPLATE AND SHOULD BE RUNNABLE!

#SBATCH --job-name=data_generation_0531-1637_1717130272.5327792
#SBATCH --output=data_generation_0531-1637_1717130272.5327792.log

### This script works for any number of nodes, Ray will find and manage all resources
#SBATCH --nodes=1
#SBATCH --chdir=/nesi/project/uoa03669/ewin313/TropicalCycloneAI/
### Give all resources to a single Ray task, ray can manage the resources internally
#SBATCH --gpus-per-task=0
#SBATCH --time=050:00:00
#SBATCH --mem-per-cpu=800MB
#SBATCH --cpus-per-task=24


# Load modules or your own conda environment here

source load-environment.sh

# ===== Call your code below =====
python ./Training\ Data\ Generation/GenerateTrainingData.py 1000 70 15 15 /nesi/project/uoa03669/ewin313/storm_data/v4 --include_grids

