#!/bin/bash
# shellcheck disable=SC2206
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS A TEMPLATE AND IT SHOULD NOT BE DEPLOYED TO PRODUCTION!
${PARTITION_OPTION}
#SBATCH --job-name=${JOB_NAME}
${GIVEN_NODE}
### This script works for any number of nodes, Ray will find and manage all resources
#SBATCH --nodes=${NUM_NODES}
#SBATCH --chdir=${CHDIR}
### Give all resources to a single Ray task, ray can manage the resources internally
#SBATCH --gpus-per-task=${NUM_GPUS_PER_NODE}
#SBATCH --time=${WALL_TIME}
#SBATCH --mem-per-cpu=${MEM}
#SBATCH --cpus-per-task=24
${QOS_DEBUG}

# Load modules or your own conda environment here

${LOAD_ENV}

# ===== Call your code below =====
${COMMAND_PLACEHOLDER}

