#!/bin/bash
# shellcheck disable=SC2206
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS MODIFIED AUTOMATICALLY FROM TEMPLATE AND SHOULD BE RUNNABLE!

#SBATCH --job-name=test_data_generation_0614-1349
#SBATCH --output=test_data_generation_0614-1349.log

### This script works for any number of nodes, Ray will find and manage all resources
#SBATCH --nodes=1
#SBATCH --chdir=/nesi/project/uoa03669/ewin313/TropicalCycloneAI/
### Give all resources to a single Ray task, ray can manage the resources internally
#SBATCH --gpus-per-task=0
#SBATCH --time=00:15:00
#SBATCH --mem-per-cpu=2GB
#SBATCH --cpus-per-task=24
#SBATCH --qos=debug

# Load modules or your own conda environment here

source load-environment.sh

# ===== Call your code below =====
python ./TrainingDataGeneration/GenerateTrainingData.py 10000 1 0 0 ./Data/run5 --include_grids

